### ISSUE TITLE
How did you calculate values in "choose[53][8]"

### ISSUE THREAD

**Issue by CuthbertJungle** [HenryRLee/PokerHandEvaluator#1]
Hi, this is great software and the explanation is very good. I think I follow everything except for how the values in the table choose[53][8] were derived and what they signify, not sure how we've gone from the 52 cards options and seven actual cards to the numbers in the table. 

please could you help me out on this.

thanks

**Comment by HenryRLee** [comment]
Hi, the choose[53][8] table comes from the mathematical combinations. So choose[n][k], often noted as 'n choose k' in maths, basically means: in a set of n elements, how many combinations you can choose to form a k elements subset. For example if you have three different colors: red, green and blue, and you want to choose two out of them, the number of combinations is 3 (red blue, red green, green blue). So 3 choose 2 (in the code is represented as choose[3][2]) is 3. [Wiki: Combination](https://en.wikipedia.org/wiki/Combination)

In terms of calculation, n choose k can be calculated from this formula: n!/k!(n-k)!, where n! is the factorial of n. However, in practice, we use the Pascal's triangle to build up this table, which would be a more efficient approach. [Wiki: Pascal's triangle](https://en.wikipedia.org/wiki/Pascal%27s_triangle)

Hope these info can help you.

**Comment by CuthbertJungle** [comment]
thanks for the prompt reply, i think i follow. do you have the code for this? i'm looking to extend your idea for looking up 2, 3 and 4 card hands so need to build a new choose table accordingly.

**Comment by CuthbertJungle** [comment]
using your provided code plugging in MAXN=53 and MAXK=8 to get the same size array as at 'choose[53][8]' in dptables.c i get different numbers. eg for row 53 in dptables.c we have values 1, 52,	1326,	22100, 270725, 2598960, 20358520, 133784560 whereas running the above code i get 140737508701408 and 6473924597557413 for the final 2 entries which are much bigger than expected.

**Comment by HenryRLee** [comment]
Sorry, I made a mistake. Change the second loop from 'j < MAXK && j <= i' to 'j < MAXK' would fix it. I'll fix the above comment as well.

**Comment by CuthbertJungle** [comment]
this is perfect ! thanks for all your help :+1:
