### ISSUE TITLE
[C++]Add more test code in unit test of the Rank type

### ISSUE THREAD

**Issue by HenryRLee** [HenryRLee/PokerHandEvaluator#18]
The unit test in https://github.com/HenryRLee/PokerHandEvaluator/blob/master/cpp/test/rank.cc only covers a small number of cases. Especially the `TestRankCategory` and `TestRankDescription`, only a full house and a straight flush appears in the test. I am expecting 3 to 5 hands from each ranking category are covered in the test code. For example, choose 3 hands from the straights, 5 hands from the pairs, etc.

You may refer to the source code in [7462.c](https://github.com/HenryRLee/PokerHandEvaluator/blob/master/cpp/src/7462.c), [rank.c](https://github.com/HenryRLee/PokerHandEvaluator/blob/master/cpp/src/rank.c) and [rank.h](https://github.com/HenryRLee/PokerHandEvaluator/blob/master/cpp/include/phevaluator/rank.h) when coding the unit test cases.

PS: When running the unit tests, you can use `./unit_tests --gtest_filter="Rank*"` to test only the test cases related to the Rank type, and skip the time-costing enumeration test.

**Comment by HenryRLee** [comment]
#19 is a good example of how this can be done.

**Comment by CaiusBonus** [comment]
Hi, is this issue still actual ? Can you assign it to me ?

**Comment by HenryRLee** [comment]
Hi @CaiusBonus, yes, more test cases are welcome. I’ll assign it to you. Thanks.

**Comment by WojtekMs** [comment]
Hello, since no one has yet helped you with this I created a PR with test cases you asked for #33. Please leave your feedback :)
