### ISSUE TITLE
Testing omaha calculation

### ISSUE THREAD

**Issue by RegentDmitry** [HenryRLee/PokerHandEvaluator#21]
Nice work! Really! 

I'm trying to evalute omaha hands EvaluateOmahaCards function but it shows 0 as result.

hand is "AsKs5d7c" and board "Ts7d8h4s2c". So I expect that inputs for evaluate_omaha_cards
 is **evaluate_omaha_cards(35, 21, 26, 11, 0, 51, 47, 13, 20)**

and line value_noflush = noflush_omaha[board_hash * 1820 + hole_hash] - gives 0

is it something wrong with noflush_omaha table or I've missed the point? Am I right that you generated it using Kev function iterating non flush hands?

**Comment by HenryRLee** [comment]
You've been doing everything right. It appears that there is a serious bug in the Omaha evaluator and its unit test code. I will try to fix the issue as soon as possible. Thank you for reporting the issue!

**Comment by HenryRLee** [comment]
Yes, I generated the hash table using Kev's function.

**Comment by HenryRLee** [comment]
I see what the problem is: the way I generated the hash table (the same way doing the unit test) does not fully cover all scenarios, causing many cases returning 0.

**Comment by RegentDmitry** [comment]
Well... I'm testing your kev function itself and it also strange for me

5 cards hand - encoding - holdem hand - kev value

Ts7d8dAsKs - 35,21,25,51,47 - A high K kicker - 166
Ts7d8dAs5d - 35,21,25,51,13 - A high T kicket - 1709
Ts7d8dAs7c - 35,21,25,51,20 - 7 pair A kicker - 4302
Ts7d8dKs7c - 35,21,25,47,20 - 7 pair K kicker - 166
Ts7d8d5d7c - 35,21,25,13,20 - 7 pair T kicker - 5646

"7 pair A kicker" must have best (lowest) kev rank here as for me...

could you please check, if you will regenerate omaha table using wrong kev it would be a pity

**Comment by HenryRLee** [comment]
Kev's evaluator, as well as my 5-card evaluator looks good to me.

Here are the source codes:

```C
#include <stdio.h>
#include <phevaluator/phevaluator.h>

int main()
{
  int rank1 = evaluate_5cards(35, 21, 25, 51, 47);
  int rank2 = evaluate_5cards(35, 21, 25, 51, 13);
  int rank3 = evaluate_5cards(35, 21, 25, 51, 20);
  int rank4 = evaluate_5cards(35, 21, 25, 47, 20);
  int rank5 = evaluate_5cards(35, 21, 25, 13, 20);

  printf("%d\n", rank1);
  printf("%d\n", rank2);
  printf("%d\n", rank3);
  printf("%d\n", rank4);
  printf("%d\n", rank5);

  return 0;
}
```

```C
#include "kev/kev_eval.h"
#include <stdio.h>

int main() {
  int rank1 = kev_eval_5cards(35, 21, 25, 51, 47);
  int rank2 = kev_eval_5cards(35, 21, 25, 51, 13);
  int rank3 = kev_eval_5cards(35, 21, 25, 51, 20);
  int rank4 = kev_eval_5cards(35, 21, 25, 47, 20);
  int rank5 = kev_eval_5cards(35, 21, 25, 13, 20);

  printf("%d\n", rank1);
  printf("%d\n", rank2);
  printf("%d\n", rank3);
  printf("%d\n", rank4);
  printf("%d\n", rank5);

  return 0;
}
```

The results of both are the same:

```
6273
6576
4894
4939
5037
```

**Comment by HenryRLee** [comment]
Oh, so you were using the `eval_5cards_fast`. That's a method using a different encoding. I exported all the useful methods in `kev/kev_eval.h`.

**Comment by RegentDmitry** [comment]
yep, I thought that it is the same because of

short kev_eval_5cards(int c1, int c2, int c3, int c4, int c5)
{
    return eval_5cards_fast(deck[c1], deck[c2], deck[c3], deck[c4], deck[c5]);
}

in tests\kev\kev_eval.c

Thanks, will try again other function

**Comment by HenryRLee** [comment]
No problem. The bug in Omaha evaluator is still valid. I will fix it ASAP.

**Comment by VVvKamper** [comment]
Hello. I'm also trying to evaluate Omaha hands but got the same bug from this issue. 

Could you please fix it or maybe help me to fix it? As i understand i need to generate new `tables_omaha.c` but i don't understand which code generates it. Is it in repo or you used something external?

**Comment by HenryRLee** [comment]
@VVvKamper Sorry this is taking so long. Basically I underestimated the number of possible Omaha hands, so many Omaha hands were overlooked when I first built the tables.

You're right. The generating code is not in the repository. I just wrote a new one, but didn't have time to run through it. Because the number of Omaha hands is too large, I estimate running the code would take days to complete. I just started running it, and hopefully I can update the table in  a couple of days. I am also placing the code in Gist so that you can have a look. https://gist.github.com/HenryRLee/a3a1901ee63b920aa9546241e71b3281

To compile it, place the file in the `cpp` folder, and run `make` to build the `libpheval.a` and then `g++ OmahaGen.cc libpheval.a -Ofast -std=c++11 -I include/` to compile the source code.

**Comment by HenryRLee** [comment]
Hi. I upgrade my generating code so that they can fully utilize 8 CPUs. They are expected to finish in 48 hours.

The code can be checked out from the Gist:
https://gist.github.com/HenryRLee/17e312343b82377c75385176e9629e6c

**Comment by HenryRLee** [comment]
Hi @RegentDmitry @VVvKamper 

I reworked on my generating code and had the Omaha table updated. As you can see the table is much more dense than before. I believe this time is correct now. It has also passes all the original test cases, as well as the example given in this issue.

```cpp
	// Community cards
	int a = 35; // Ts
	int b = 21; // 7d
	int c = 26; // 8h
	int d = 11; // 4s
	int e = 0; // 2c

        // Player cards
	int f = 51; // As
	int g = 47; // Ks
	int h = 13; // 5d
	int i = 20; // 7c

        // The result is 4894 (7 7 A T 8)
	int value = phevaluator::EvaluateOmahaCards(a, b, c, d, e, f, g, h, i).value();
```

Moreover, I would add more test cases for the Omaha hands. But covering all the possible Omaha hands is not feasible.

**Comment by HenryRLee** [comment]
I am now randomly selecting 9 cards (and they are not in an order) in the unit test. They have all passed.
So I believe this issue is fixed.

**Comment by HenryRLee** [comment]
Thank you for reporting the issue!

**Comment by RegentDmitry** [comment]
Thank you so much! will try your updates soon
