### ISSUE TITLE
Help to compile properly needed

### ISSUE THREAD

**Issue by msm1089** [HenryRLee/PokerHandEvaluator#26]
I'm a total newbie when it comes to C/C++. I'm hoping someone can help with a problem I encounter when following the instructions.

All steps in the guide worked:

mkdir -p build
cd build
cmake ..
make

For the last one, I had to go back up to the cpp directory. I see the libpheval.a file as expected, in the cpp folder.

However, no unit_test binary is created. I searched the whole folder of PokerHandEvaluator for 'unit_test', only 2 files are returned: unit_tests.vxproj and unit_tests.vxproj.filters

Anything I should be doing/not doing here?

**Comment by HenryRLee** [comment]
I suppose in Windows environment, no unit test binary will be generated.
