### ISSUE TITLE
Tables for 6 cards

### ISSUE THREAD

**Issue by thlorenz** [HenryRLee/PokerHandEvaluator#3]
Hey, super nice repo and the docs are very interesting.

I was wondering if you could add the tables for 6 cards to the repo or provide the code to do so?
Those are needed if you're looking at hand ranks on the Turn of hold'em or if you want to calculate draws.

Would greatly appreciate it. Thanks.

**Comment by HenryRLee** [comment]
Hi thlorenz, thank you for the suggestion. I'll be glad to code the 6-card evaluator and add it to the repository. But it might take a couple of days.

**Comment by thlorenz** [comment]
Cool, no sweats, let me know if I can help.
The evaluator should be easy enough once you have the table .. that's the part that I'm not sure how to implement, but I'm looking forward to you adding it :)

Thanks.

**Comment by HenryRLee** [comment]
No problem.

Actually, you can still use the same 'dp' table for the 6-card evaluation, that table covers all hands no greater than 7 cards. With a slight modification to the hash function, you can get the hash key of a 6-card hand easily.

However the assignment of the hash table would be more problematic. What I am planning to do is iterating all possible 6-card hands, and as for each hand, evaluate all 5-card hand combinations and choose the best out of it.

**Comment by HenryRLee** [comment]
Hi thlorenz, the 6-card hand evaluation code has been pushed to the master branch.

**Comment by thlorenz** [comment]
Awesome, that was super quick.
I ported your code to JavaScript so people can use it with Node.js and in the browser.
However I'd like to release under MIT and don't really like to include the comments on top of each file.

Would that be ok with you? Haven't pushed to github yet as I wanted to get your feedback first.

**Comment by HenryRLee** [comment]
Hi Thorsten, I guess it's fine to change the license to MIT in your source code.

**Comment by thlorenz** [comment]
Awesome I'll clean things up tonight and push it up.
I added an API on top of what you did, so you can do things like:

```js
const rank = rankBoard( 'Th 3d Jh Qh Kh Ah')
assert.equal(rank, STRAIGH_FLUSH)
```
Also added a bunch more tests .. some of which you maybe able to port back to C.
I'll shoot you the link once it's up and of course I'll link to your repo in the readme.
BTW the JS version is about 3x slower than your C version.

**Comment by HenryRLee** [comment]
That's good. I'm glad you are improving it. Thank you.

**Comment by thlorenz** [comment]
OK [it's up](https://github.com/thlorenz/phe). Also published to npm so people can quickly install it.
Thanks again for your awesome work and for implementing the 6 card feature.

Closing this issue now since it's obviously solved ;)

**Comment by HenryRLee** [comment]
No problem. And thank you for sharing your repository with me.
