### ISSUE TITLE
Feature request: describe card name(e.g. "Qc")

### ISSUE THREAD

**Issue by azriel1rf** [HenryRLee/PokerHandEvaluator#37]
The describe method for the Card class might be convenient as the Rank::describeSampleHand() is.

example (C++):
```c++
auto c1 = phevaluator::Card("2c");
std::cout << c1.describeName() << "\n"; // 2c
std::cout << c1.describeSuit() << "\n"; // c
std::cout << c1.describeRank() << "\n"; // 2
std::cout << std::string(c1) << "\n"; // 2c
// std::cout << c1 << "\n"; // 0. overloading << is too much.

auto c2 = phevaluator::Card("2C"); // case insensitive. doesn't store original string
std::cout << c2.describeName() << "\n"; // 2c

phevaluator::Card c3{0};
std::cout << c3.describeName() << "\n"; // 2c
```
example (Python):
```python
c1 = Card("2c")
print(c1.describe_name()) # 2c
...
print(str(c1)) # 2c
```

Sounds good? Then, I will write it both in C++ and Python and send PR.
However, I'm not sure if the function name "describeName" is appropriate whereas "describeSuit" and "describeRank" seem not bad.
Could you tell your opinion? @HenryRLee

**Comment by HenryRLee** [comment]
That sounds good. A pull request is very welcomed. :)

**Comment by HenryRLee** [comment]
@azriel1rf I think we can name them `describeCard`, `describeSuit` and `describeRank`?
