### ISSUE TITLE
Code style for Python

### ISSUE THREAD

**Issue by azriel1rf** [HenryRLee/PokerHandEvaluator#38]
The standard Python code style recommends 4-space indentation.
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
On top of that, we can use formatter withtout user-defined configuration when it's 4-space.

Hence, I formatted `.py` codes by the standard formatter and made some configuration to ignore inaproperiate files(both file-by-file and line-by-line) with keeping in mind transparency and reproducibility.
After that, I attempted to open PR (#39) and was aware of the guideline of 2-space indentation.

Depending on the editor to use, switching indentation may be uncomfortable and 4-space indentation can be felt something odd to most of developers except Python users.
`.editorconfig` allows to switch settings by file-extension but it's unclear whether it's usable or not.
https://editorconfig.org/

How do you think?

**Comment by HenryRLee** [comment]
Thank you. I updated the contribution guide as well.
