### ISSUE TITLE
Issue with hash.py when importing python module

### ISSUE THREAD

**Issue by bsstibich** [HenryRLee/PokerHandEvaluator#67]
I'm attempting to use the phevaluator python module for a personal project of mine however when trying to import I get an error in regards to the hash.py file provided with 0.5.1

I've not been able to actually attempt to utilize the module yet due to the error shutting down the program right at the import step.

Here is the error I receive:

_Traceback (most recent call last):
  File "/home/bsstibich/Documents/poker-board-evaluator/main.py", line 1, in <module>
    from phevaluator import evaluate_cards
  File "/home/bsstibich/.local/lib/python3.8/site-packages/phevaluator/__init__.py", line 2, in <module>
    from . import hash as hash_  # FIXME: `hash` collides to built-in function
  File "/home/bsstibich/.local/lib/python3.8/site-packages/phevaluator/hash.py", line 5, in <module>
    def hash_quinary(quinary: list[int], num_cards: int) -> int:
TypeError: 'type' object is not subscriptable_

Any help would be appreciated because this module is the only poker module I could find that does exactly what I need for my specific project and would love to be able to use it.

**Comment by TheTechWalrus** [comment]
Your python version must be under 3.9 (since that's when support for type hinting using standard collections was added).

To fix this, you can either upgrade to 3.9, or if you must use the older version - you could find all instances of `:list`  within function signatures and replace them with `typing.List` (don't forget to import the typing module).

**Comment by bsstibich** [comment]
This solved my problem thank you. 

I guess its been a long time since I've updated python I was on 3.7 @_@
