### ISSUE TITLE
'type' object is not subscriptable----PYTHON

### ISSUE THREAD

**Issue by vinoshuai-NLP** [HenryRLee/PokerHandEvaluator#72]
Thanks for your contributions.

When I implemented it using python 3.8, I meet the bug:

[/usr/local/lib/python3.8/dist-packages/phevaluator/__init__.py](https://localhost:8080/#) in <module>
      1 """Package for evaluating a poker hand."""
----> 2 from . import hash as hash_  # FIXME: `hash` collides to built-in function
      3 from . import tables
      4 from .card import Card
      5 from .evaluator import _evaluate_cards, evaluate_cards

[/usr/local/lib/python3.8/dist-packages/phevaluator/hash.py](https://localhost:8080/#) in <module>
      3 
      4 
----> 5 def hash_quinary(quinary: list[int], num_cards: int) -> int:
      6     """Hash list of cards.
      7 

TypeError: 'type' object is not subscriptable

So are there any solutions?
THANKS

**Comment by azriel1rf** [comment]
It would be nice to support Python 3.8.
The `list[int]` caused that error.
I am going to fix it.
