### ISSUE TITLE
CMakeLists.txt tries to install header that doesn't exist

### ISSUE THREAD

**Issue by jlack1987** [HenryRLee/PokerHandEvaluator#84]
See [this line](https://github.com/HenryRLee/PokerHandEvaluator/blob/master/cpp/CMakeLists.txt#L42). It is trying to install `phevaluator5.h`, but that file doesn't exist in the project. Based on the files in the project it looks like the `5` just needs to be removed from the file name? It compiles if I remove that `5`. Lmk if that's the desired fix and I can MR it.

**Comment by HenryRLee** [comment]
Yes, that's a mistake. We should remove the character `5`.  Would you like to create a PR to fix it?

**Comment by jlack1987** [comment]
Yeah MR [here](https://github.com/HenryRLee/PokerHandEvaluator/pull/85)

**Comment by HenryRLee** [comment]
It's merged. Thank you for your contribution!
