### ISSUE TITLE
Pypi Website Typo Fix

### ISSUE THREAD

**Issue by JAM-Beni** [HenryRLee/PokerHandEvaluator#88]
Due to the commit I created, on the website: https://pypi.org/project/phevaluator/ the library usage part is not ideal with VSCode.

The code `from phevaluator import evaluate_cards` produces `Any` on VSCode:
<img src="https://github.com/HenryRLee/PokerHandEvaluator/assets/140108720/7bac05e1-ff03-4f4d-b5c2-3779a6630754" width=50% height=50%>

`from phevaluator.evaluator import evaluate_cards` should be added so it provides the documentation:
<img src="https://github.com/HenryRLee/PokerHandEvaluator/assets/140108720/54b29e38-a190-450f-87ca-306d830952fb" width=60% height=60%>

I'm not quite sure how to fix this as it still imports without error. My inability to fix this is why I suggest to simply update the website portion.

**Comment by HenryRLee** [comment]
I think you can update the README.md file in the python directory, and then the PyPi website will get reflected.

https://github.com/HenryRLee/PokerHandEvaluator/blob/master/python/README.md

**Comment by JAM-Beni** [comment]
Whoops, I checked and I definitely missed it.

**Comment by HenryRLee** [comment]
Ok, it turns out that, in order to update the website, I need to push another PyPi package to include that README.md change.

Anyway, your change is now visible in the website. Thanks for your change!
