### ISSUE TITLE
Refactor `_evaluate_omaha_cards` function for simplicity

### ISSUE THREAD

**Issue by azriel1rf** [HenryRLee/PokerHandEvaluator#92]
The `_evaluate_omaha_cards` in [evaluator_omaha.py](../blob/master/python/phevaluator/evaluator_omaha.py) is currently too complex and could benefit from refactoring.
Its complexity makes it difficult to understand and maintain.

Here's the function in question:
```Python
def _evaluate_omaha_cards(community_cards: list[int], hole_cards: list[int]) -> int:
    # ...
```

This function performs several tasks, including counting suits, determining flushes, and calculating hashes. These tasks could potentially be broken down into smaller, more manageable functions.

Additionally, the function uses magic numbers (like 10000 for `value_flush` and `value_noflush`), which could be replaced with named constants to improve readability.

Finally, the function is quite long, which makes it harder to understand at a glance. Breaking it down into smaller functions would make it easier to understand and test.

Acceptance Criteria:
* The _evaluate_omaha_cards function is broken down into smaller, more manageable functions.
* Magic numbers are replaced with named constants.
* The refactored code is covered by unit tests to ensure it still works as expected.

**Comment by ParthShitole** [comment]
I would like to pick this up.

**Comment by HenryRLee** [comment]
Thanks @ParthShitole! If you have questions, feel free to ask us.

**Comment by ParthShitole** [comment]
I have refactored the code, do you expect unit tests for all new functions in the same PR

**Comment by HenryRLee** [comment]
If the `_evaluate_omaha_cards` function is still there, and you are just adding new functions so that `_evaluate_omaha_cards` calls these new functions, then no new unit test is needed. We just need to make sure `_evaluate_omaha_cards` still passes the old unit tests.

**Comment by ParthShitole** [comment]
i have just added new functions to _evaluate_omaha_cards, the old tests are passing . I'll skip writing tests then, thanks for the clarification

**Comment by ParthShitole** [comment]
Can you help me with this
```
root@LAPTOP-264SBR7M:/mnt/c/Users/REDACTED/OneDrive/Desktop/PokerHandEvaluator# git commit -m "Refactor _evaluate_omaha_cards and simplify it"
An error has occurred: InvalidConfigError:
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='mypy')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
```

**Comment by HenryRLee** [comment]
That's the `pre-commit` dependency. Can you please try this?

```
pip install pre-commit
pre-commit install
```

Reference:
https://github.com/HenryRLee/PokerHandEvaluator/blob/develop/CONTRIBUTING.md#pre-commit

**Comment by ParthShitole** [comment]
Yes i did that,
```
root@LAPTOP-264SBR7M:/mnt/c/Users/REDACTED/OneDrive/Desktop/PokerHandEvaluator# pre-commit install
pre-commit installed at .git/hooks/pre-commit
```
Still facing the issue

**Comment by HenryRLee** [comment]
https://github.com/psf/black/issues/4065#issuecomment-1821277094

Folks are saying this is because the `pre-commit` version in your environment is lower than 3.2.0. Can you double check the version using `pre-commit --version`?

If it is low, can you upgrade it? (If it is a Python package you may just try `pip install --upgrade pre-commit`.)

**Comment by ParthShitole** [comment]
Yes that was the issue, i updated it and now it works. Thanks for the help.

**Comment by ParthShitole** [comment]
@HenryRLee I have raised a PR. Can you check if the changes satisfy the requirements .

**Comment by HenryRLee** [comment]
@ParthShitole Thanks for the PR!

It looks good generally, and the actions are all green. That's very nice! We'll review the code changes in detail.
